version: "3.4"

# Development environment override
services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/srv/app
    environment:
      NODE_ENV: development
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/srv/app
    environment:
      NODE_ENV: development
    ports:
      - "3100:3000"