version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      target: prod
    environment:
      - REACT_APP_BACKEND_URL
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: prod
    environment:
      - MONGODB_CONNECTION_URI
      - BACKEND_PORT
      - REACT_APP_OPEN_WEATHER_MAP_API_KEY
      - RSS_FEED_URL
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    expose:
      - "27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: